### PR TITLE
Code style cleanup with SwiftLint

### PR DESCRIPTION
**Pull request by ghv**

### CODE REVIEW

**Review by adamkaplan — APPROVED** [review]
Nice, thanks for the cleanup!

**Comment by adamkaplan** [comment]
Using for anything interesting @ghv ?

**Comment by ghv** [comment]
I have a few ideas. Nothing to announce yet. However, I will work on a macOS example for this.

**Comment by adamkaplan** [comment]
Very cool, would love to see what changes are required for macOS.

Anything you need, if it's public-safe, we can discuss as `Issues` here on the repo. Otherwise, we can chat on Oath Slack.

**Pull request merged**
